### ISSUE TITLE
Crashing for no reason.

### ISSUE THREAD

**Issue by ronrishadi** [Nilsen84/lunar_launcher_inject#10]
Crashing for no reason.

**Comment by MuriloFangel** [comment]
bump

**Comment by NotRati** [comment]
pump

**Comment by Nilsen84** [comment]
You need to place the executable in a directory with no other jar files apart from the agents you want to use. If you've already done this you should bring the issue up along with crash logs to the appropriate agent developers (https://discord.gg/SHZUYWhwDP for weave).
