### ISSUE TITLE
How does this work (with mac)

### ISSUE THREAD

**Issue by Husk-ees** [Nilsen84/lunar_launcher_inject#2]
title^

**Comment by Husk-ees** [comment]
like how woudl i run this on mac

**Comment by Nilsen84** [comment]
Just download the executable and start it. Make sure you have lunar installed tho.

**Comment by Husk-ees** [comment]
the lunar-launcher-inject file is a document, not an app (for mac)

**Comment by Nilsen84** [comment]
Can you send a screenshot

**Comment by Monmcgt** [comment]
open a terminal in the same directory as the `lunar-launcher-inject-mac` file then run
```
$ chmod +x  lunar-launcher-inject-mac
$ ./lunar-launcher-inject-mac
```

**Comment by a7md8762** [comment]
says: 

> failed to locate the lunar launcher executable, try passing it by argument: '/usr/bin/lunarclient' does not exist

**Comment by cringeoverdose** [comment]
> says:
> 
> > failed to locate the lunar launcher executable, try passing it by argument: '/usr/bin/lunarclient' does not exist

were you ever able to find a solution for this?

**Comment by Husk-ees** [comment]
open a terminal in the same directory as the lunar-launcher-inject-mac file then run

$ chmod +x  lunar-launcher-inject-mac
$ ./lunar-launcher-inject-mac

**Comment by stufa21351** [comment]
You cannot open terminal in t he same directory as the file, also the command doesnt exist

**Comment by Nilsen84** [comment]
* Create a new folder anywhere
* Download the mac executable and move it into said folder
* Open a terminal in the same folder and run `chmod +x lunar-launcher-inject-mac-1.2.0`

To run the launcher you have to open a terminal and run `./lunar-launcher-inject-mac-1.2.0`
(it might be possible to do from finder)
