### ISSUE TITLE
Launching error

### ISSUE THREAD

**Issue by badgecillt** [Nilsen84/lunar_launcher_inject#7]
Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: dee55a0db9bd1c1e01dafbd877b8ea5c68a6bf59f7b0903b276931d4e6f7c839
Launcher Version: 2.15.1
OS: win32 x64
Game Version: /master
Launch Type: OFFLINE

**Comment by TheXiaoma** [comment]
me too
----
Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 4b1802f34d23c070e756d834910c56f80280432a1fd857686c52d039a4772edf
Launcher Version: 2.15.1
OS: win32 x64
Game Version: 1.8.9/master
Launch Type: OFFLINE

**Comment by cubigiabinh** [comment]
Perhaps you guys have run Lunar Client with the RavenWeave. I get the same report here:

**We have different launcher ID**

`Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 948ffd5e5af36a6d4f579da71dbcecc98a9a0efc0752b6fee7b2971501259044
Launcher Version: 2.15.1
OS: win32 x64
Game Version: 1.8.9/development
Launch Type: OFFLINE`

I tried with the stable branch and still get the same:

`Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 948ffd5e5af36a6d4f579da71dbcecc98a9a0efc0752b6fee7b2971501259044
Launcher Version: 2.15.1
OS: win32 x64
Game Version: 1.8.9/master
Launch Type: OFFLINE`

We basically cannot use RavenWeave with lunar-launcher-inject, but I bet other agents still work (such as HitDelayFix or CrackedAccount). I saw a video on YouTube (from the Ravenb++ discord server) on him launching lunar with Ravenb++. That's what I know by far, as I've tried to delete the RavenWeave and it launched perfectly.

**Comment by Nilsen84** [comment]
^
You need to place the LLI executable in a directory with no other jar files apart from the agents you want to use. If you've already done this you should bring the issue up along with crash logs to the appropriate agent developers (https://discord.gg/SHZUYWhwDP for weave).
