### ISSUE TITLE
How to make this work on mac

### ISSUE THREAD

**Issue by BlueErrorXD123** [Nilsen84/lunar_launcher_inject#8]
I cant get this running on mac

**Comment by Nilsen84** [comment]
* Create a new folder anywhere
* Download the mac executable and move it into said folder
* Open a terminal in the same folder and run `chmod +x lunar-launcher-inject-mac-1.2.0`

To run the launcher you have to open a terminal and run `./lunar-launcher-inject-mac-1.2.0` (it might be possible to do from finder idk tho)
